// <auto-generated />
using System;
using JobMagnet.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobMagnet.Infrastructure.Migrations
{
    [DbContext(typeof(JobMagnetDbContext))]
    partial class JobMagnetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContactTypeId");

                    b.HasIndex("ResumeId");

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconClass")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IconUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ContactTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bx-envelope",
                            IsDeleted = false,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bx-mobile",
                            IsDeleted = false,
                            Name = "Mobile Phone"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bx-phone",
                            IsDeleted = false,
                            Name = "Home Phone"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bx-phone-call",
                            IsDeleted = false,
                            Name = "Work Phone"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bx-globe",
                            IsDeleted = false,
                            Name = "Website"
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-linkedin",
                            IsDeleted = false,
                            Name = "LinkedIn"
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-github",
                            IsDeleted = false,
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-twitter",
                            IsDeleted = false,
                            Name = "Twitter"
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-facebook",
                            IsDeleted = false,
                            Name = "Facebook"
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-instagram",
                            IsDeleted = false,
                            Name = "Instagram"
                        },
                        new
                        {
                            Id = 11,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-youtube",
                            IsDeleted = false,
                            Name = "YouTube"
                        },
                        new
                        {
                            Id = 12,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-whatsapp",
                            IsDeleted = false,
                            Name = "WhatsApp"
                        },
                        new
                        {
                            Id = 13,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-telegram",
                            IsDeleted = false,
                            Name = "Telegram"
                        },
                        new
                        {
                            Id = 14,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-snapchat",
                            IsDeleted = false,
                            Name = "Snapchat"
                        },
                        new
                        {
                            Id = 15,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-pinterest",
                            IsDeleted = false,
                            Name = "Pinterest"
                        },
                        new
                        {
                            Id = 16,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-skype",
                            IsDeleted = false,
                            Name = "Skype"
                        },
                        new
                        {
                            Id = 17,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-discord",
                            IsDeleted = false,
                            Name = "Discord"
                        },
                        new
                        {
                            Id = 18,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-twitch",
                            IsDeleted = false,
                            Name = "Twitch"
                        },
                        new
                        {
                            Id = 19,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-tiktok",
                            IsDeleted = false,
                            Name = "TikTok"
                        },
                        new
                        {
                            Id = 20,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-reddit",
                            IsDeleted = false,
                            Name = "Reddit"
                        },
                        new
                        {
                            Id = 21,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IconClass = "bx bxl-vimeo",
                            IsDeleted = false,
                            Name = "Vimeo"
                        });
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactTypeAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ContactTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("ContactTypeId");

                    b.ToTable("ContactAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Correo Electrónico",
                            ContactTypeId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "E-mail",
                            ContactTypeId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Phone",
                            ContactTypeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfonos",
                            ContactTypeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono Móvil",
                            ContactTypeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Celular",
                            ContactTypeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Móvil",
                            ContactTypeId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono Fijo",
                            ContactTypeId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono de Casa",
                            ContactTypeId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono Casa",
                            ContactTypeId = 3,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono Trabajo",
                            ContactTypeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono Oficina",
                            ContactTypeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono de Trabajo",
                            ContactTypeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Teléfono de Oficina",
                            ContactTypeId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Web Site",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Web-site",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Sitio Web",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Página Web",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Blog",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Portafolio",
                            ContactTypeId = 5,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 21,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "X",
                            ContactTypeId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 22,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Wasap",
                            ContactTypeId = 12,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 23,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Whatsapp",
                            ContactTypeId = 12,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.EducationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InstitutionLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstitutionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SummaryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("Educations", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.PortfolioGalleryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("PorfolioGalleryItems", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ProfileEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondLastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.PublicProfileIdentifierEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileSlugUrl")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("ProfileSlugUrl")
                        .IsUnique()
                        .HasDatabaseName("IX_PublicProfileIdentifier_Identifier");

                    b.ToTable("PublicProfileIdentifier");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ResumeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.Property<string>("Suffix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Resumes", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ServiceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ServiceGalleryItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<long>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceGalleryItems", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<long>("SkillSetId")
                        .HasColumnType("bigint");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillSetId");

                    b.HasIndex("SkillTypeId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SkillCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "General"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsDeleted = false,
                            Name = "Software Development"
                        });
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillSet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("SkillSets");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SkillTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/html5",
                            IsDeleted = false,
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/css3",
                            IsDeleted = false,
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/javascript",
                            IsDeleted = false,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/dotnet",
                            IsDeleted = false,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/typescript",
                            IsDeleted = false,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 6,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/angular",
                            IsDeleted = false,
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 7,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/postgresql",
                            IsDeleted = false,
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 8,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/react",
                            IsDeleted = false,
                            Name = "React"
                        },
                        new
                        {
                            Id = 9,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/bootstrap",
                            IsDeleted = false,
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = 10,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/vuedotjs",
                            IsDeleted = false,
                            Name = "Vue"
                        },
                        new
                        {
                            Id = 11,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/git",
                            IsDeleted = false,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 12,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/blazor",
                            IsDeleted = false,
                            Name = "Blazor"
                        },
                        new
                        {
                            Id = 13,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/rabbitmq",
                            IsDeleted = false,
                            Name = "RabbitMQ"
                        },
                        new
                        {
                            Id = 14,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CategoryId = 2,
                            IconUrl = "https://cdn.simpleicons.org/docker",
                            IsDeleted = false,
                            Name = "Docker"
                        });
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillTypeAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkillTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("SkillTypeId");

                    b.ToTable("SkillTypeAliases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "JS",
                            IsDeleted = false,
                            SkillTypeId = 3
                        },
                        new
                        {
                            Id = 2,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "TS",
                            IsDeleted = false,
                            SkillTypeId = 5
                        },
                        new
                        {
                            Id = 3,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Postgres",
                            IsDeleted = false,
                            SkillTypeId = 7
                        },
                        new
                        {
                            Id = 4,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Vue.js",
                            IsDeleted = false,
                            SkillTypeId = 10
                        },
                        new
                        {
                            Id = 5,
                            AddedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            Alias = "Rabbit MQ",
                            IsDeleted = false,
                            SkillTypeId = 13
                        });
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.SummaryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Summaries", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.TalentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Talents", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.TestimonialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfileId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("Testimonials", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.WorkExperienceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("SummaryId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SummaryId");

                    b.ToTable("WorkExperiences", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.WorkResponsibilityEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("WorkExperienceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkExperienceId");

                    b.ToTable("WorkResponsibilities", (string)null);
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactInfo", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.Contact.ContactType", "ContactType")
                        .WithMany()
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMagnet.Domain.Core.Entities.ResumeEntity", null)
                        .WithMany("ContactInfo")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactType");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactTypeAlias", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.Contact.ContactType", null)
                        .WithMany("Aliases")
                        .HasForeignKey("ContactTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.EducationEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.SummaryEntity", "Summary")
                        .WithMany("Education")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.PortfolioGalleryEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithMany("PortfolioGallery")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.PublicProfileIdentifierEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", null)
                        .WithMany("PublicProfileIdentifiers")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ResumeEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", null)
                        .WithOne("Resume")
                        .HasForeignKey("JobMagnet.Domain.Core.Entities.ResumeEntity", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ServiceEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithOne("Services")
                        .HasForeignKey("JobMagnet.Domain.Core.Entities.ServiceEntity", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ServiceGalleryItemEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ServiceEntity", "Service")
                        .WithMany("GalleryItems")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.Skill", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.Skills.SkillSet", null)
                        .WithMany("Skills")
                        .HasForeignKey("SkillSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMagnet.Domain.Core.Entities.Skills.SkillType", "SkillType")
                        .WithMany()
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillType");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillSet", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithOne("SkillSet")
                        .HasForeignKey("JobMagnet.Domain.Core.Entities.Skills.SkillSet", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillType", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.Skills.SkillCategory", "Category")
                        .WithMany("SkillTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillTypeAlias", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.Skills.SkillType", null)
                        .WithMany("Aliases")
                        .HasForeignKey("SkillTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.SummaryEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithOne("Summary")
                        .HasForeignKey("JobMagnet.Domain.Core.Entities.SummaryEntity", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.TalentEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithMany("Talents")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.TestimonialEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.ProfileEntity", "Profile")
                        .WithMany("Testimonials")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.WorkExperienceEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.SummaryEntity", "Summary")
                        .WithMany("WorkExperiences")
                        .HasForeignKey("SummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Summary");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.WorkResponsibilityEntity", b =>
                {
                    b.HasOne("JobMagnet.Domain.Core.Entities.WorkExperienceEntity", "WorkExperience")
                        .WithMany("Responsibilities")
                        .HasForeignKey("WorkExperienceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Contact.ContactType", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ProfileEntity", b =>
                {
                    b.Navigation("PortfolioGallery");

                    b.Navigation("PublicProfileIdentifiers");

                    b.Navigation("Resume");

                    b.Navigation("Services");

                    b.Navigation("SkillSet");

                    b.Navigation("Summary");

                    b.Navigation("Talents");

                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ResumeEntity", b =>
                {
                    b.Navigation("ContactInfo");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.ServiceEntity", b =>
                {
                    b.Navigation("GalleryItems");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillCategory", b =>
                {
                    b.Navigation("SkillTypes");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillSet", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.Skills.SkillType", b =>
                {
                    b.Navigation("Aliases");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.SummaryEntity", b =>
                {
                    b.Navigation("Education");

                    b.Navigation("WorkExperiences");
                });

            modelBuilder.Entity("JobMagnet.Domain.Core.Entities.WorkExperienceEntity", b =>
                {
                    b.Navigation("Responsibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
