trigger:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  vmImageName: 'ubuntu-latest'

stages:
  - stage: CodeQuality
    displayName: 'Code Quality and Testing'
    jobs:
      - template: templates/code-quality-template.yml