name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache SonarQube packages and scanner
        uses: actions/cache@v4
        with:
          path: |
            ~/.sonar/cache
            ~/.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner-${{ hashFiles('**/pom.xml', '**/build.gradle', '**/package-lock.json', '**/composer.lock') }}
          restore-keys: ${{ runner.os }}-sonar-scanner-

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:/home/runner/.dotnet/tools"

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore and build project
        run: dotnet build

      - name: Run Unit Tests and Collect Coverage
        working-directory: ${{ github.workspace }}
        run: |
          dotnet test ./tests/JobMagnet.Unit.Tests/JobMagnet.Unit.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./tests/JobMagnet.Unit.Tests/coverage.opencover.xml --logger:trx
          dotnet test ./tests/JobMagnet.Unit.Tests/JobMagnet.Unit.Tests.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./tests/JobMagnet.Unit.Tests/coverage.opencover.xml 
          echo "Listing files in JobMagnet.Unit.Tests directory:" 
          ls -l ./tests/JobMagnet.Unit.Tests
        env:
          OpenTelemetry__Enabled: 'false'
          Serilog__MinimumLevel__Default: 'Critical'

      - name: Verify Coverage Report
        run: |
          ls -l ./tests/JobMagnet.Unit.Tests/coverage.opencover.xml

      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: bash
        run: |
          export PATH="$PATH:/home/runner/.dotnet/tools"
          dotnet-sonarscanner begin /k:"henksandoval_JobMagnetic-BackEnd" /o:"henksandoval" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.projectBaseDir="${{ github.workspace }}" \
            /d:sonar.coverageReportPaths=".tests/JobMagnet.Unit.Tests/coverage.opencover.xml"
          dotnet build
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"